config/routes.rb
Refinery::Application.routes.draw do
  get '/contact', :to => 'inquiries#new', :as => 'new_inquiry'
  resources :contact,
            :only => :create,
            :as => :inquiries,
            :controller => 'inquiries' do
    collection do
      get :thank_you
    end
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :inquiries, :only => [:index, :show, :destroy] do
      collection do
        get :spam
      end
      member do
        get :toggle_spam
      end
    end
    resources :inquiry_settings, :only => [:edit, :update]
  end
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  validates :name, :presence => true
  validates :message, :presence => true
  validates :company, :presence => true
  validates :email, :presence => true
  
  acts_as_indexed :fields => [:name, :email, :message, :phone, :company, :address, :city, :state, :zip, :country]

  default_scope :order => 'created_at DESC' # previously scope :newest

  def self.latest(number = 7, include_spam = true)
    include_spam ? limit(number) : ham.limit(number)
  end

end

app/models/inquiry_setting.rb
class InquirySetting < ActiveRecord::Base

  def self.confirmation_body
    RefinerySetting.find_or_set(:inquiry_confirmation_body,
      "Thank you for your inquiry %name%,\n\nThis email is a receipt to confirm we have received your inquiry and we'll be in touch shortly.\n\nThanks."
    )
  end

  def self.confirmation_subject
    RefinerySetting.find_or_set(:inquiry_confirmation_subject,
                                "Thank you for your inquiry")
  end

  def self.confirmation_subject=(value)
    # handles a change in Refinery API
    if RefinerySetting.methods.map(&:to_sym).include?(:set)
      RefinerySetting.set(:inquiry_confirmation_subject, value)
    else
      RefinerySetting[:inquiry_confirmation_subject] = value
    end
  end

  def self.notification_recipients
    RefinerySetting.find_or_set(:inquiry_notification_recipients,
                                ((Role[:refinery].users.first.email rescue nil) if defined?(Role)).to_s)
  end

  def self.notification_subject
    RefinerySetting.find_or_set(:inquiry_notification_subject,
                                "New inquiry from your website")
  end

end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < Admin::BaseController

  crudify :inquiry, :title_attribute => "name", :order => "created_at DESC"
  helper_method :group_by_date

  before_filter :find_all_ham, :only => [:index]
  #before_filter :find_all_spam, :only => [:spam]
  #before_filter :get_spam_count, :only => [:index, :spam]

  def index
    @inquiries = @inquiries.with_query(params[:search]) if searching?
    @inquiries = @inquiries.paginate({:page => params[:page]})
  end

  def spam
    self.index
    render :action => 'index'
  end

  def toggle_spam
    find_inquiry
    @inquiry.toggle!(:spam)

    redirect_to :back
  end

protected

  def find_all_ham
    @inquiries = Inquiry.all
  end

  def find_all_spam
    @inquiries = Inquiry.spam
  end

  def get_spam_count
    @spam_count = Inquiry.count(:conditions => {:spam => true})
  end

end

app/controllers/admin/inquiry_settings_controller.rb
class Admin::InquirySettingsController < Admin::BaseController

  crudify :refinery_setting,
          :title_attribute => "name",
          :order => 'name ASC',
          :redirect_to_url => "admin_inquiries_url"

  before_filter :set_url_override?, :only => [:edit, :update]
  after_filter :save_subject_for_confirmation?, :only => :update
  around_filter :rewrite_flash?, :only => :update

protected
  def rewrite_flash?
    yield

    flash[:notice] = flash[:notice].to_s.gsub(/(\'.*\')/) {|m| m.titleize}.gsub('Inquiry ', '')
  end

  def save_subject_for_confirmation?
    InquirySetting.confirmation_subject = params[:subject] if params.keys.include?('subject')
  end

  def set_url_override?
    @url_override = admin_inquiry_setting_url(@refinery_setting, :dialog => from_dialog?)
  end

  def find_refinery_setting
    # ensure that we're dealing with the name of the setting, not the id.
    begin
      if params[:id].to_i.to_s == params[:id]
        params[:id] = RefinerySetting.find(params[:id]).name.to_s
      end
    rescue
    end

    # prime the setting first, if it's valid.
    if InquirySetting.methods.map(&:to_sym).include?(params[:id].to_s.gsub('inquiry_', '').to_sym)
      InquirySetting.send(params[:id].to_s.gsub('inquiry_', '').to_sym)
    end
    @refinery_setting = RefinerySetting.find_by_name(params[:id])
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  before_filter :find_page, :only => [:create, :new]

  def thank_you
    @page = Page.find_by_link_url("/contact/thank_you", :include => [:parts, :slugs])
  end

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])

    if verify_recaptcha(:model => @inquiry, :message => "ReCaptcha is Incorrect!") && @inquiry.save
      
      #removing spam filter
      if @inquiry.save!
        begin
          InquiryMailer.notification(@inquiry, request).deliver
        rescue
          logger.warn "There was an error delivering an inquiry notification.\n#{$!}\n"
        end
        begin
          InquiryMailer.confirmation(@inquiry, request).deliver
        rescue
          logger.warn "There was an error delivering an inquiry confirmation:\n#{$!}\n"
        end
      end
      redirect_to thank_you_inquiries_url
    else
      render :action => 'new'
    end
  end

  protected

  def find_page
    @page = Page.find_by_link_url('/contact', :include => [:parts, :slugs])
  end

end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/admin/inquiries/_inquiry.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= link_to inquiry.name, admin_inquiry_url(inquiry) %> <%= t('.said') %>
    <span class="preview"><%= truncate(strip_tags(inquiry.message), :length => 60) -%></span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('delete.png'), admin_inquiry_url(inquiry),
              { :method => :delete, 
                :confirm => t('shared.admin.delete.message', :title => inquiry.name) },
                :class => "cancel confirm-delete",
                :title => t('admin.inquiries.delete') -%>

    <%= link_to refinery_icon_tag('zoom.png'), admin_inquiry_url(inquiry),
                :title => t('.read_inquiry') -%>

    <!-- hiding because we're not using ham/spam
    <%# if inquiry.spam? %>
      <%#= link_to refinery_icon_tag('email.png'), toggle_spam_admin_inquiry_url(inquiry),
                  :title => t('.mark_as_ham') -%>
    <%# else %>
      <%#= link_to refinery_icon_tag('bin_closed.png'), toggle_spam_admin_inquiry_url(inquiry),
                  :title => t('.mark_as_spam') -%>
    <%# end %>-->
  </span>
</li>

app/views/admin/inquiries/_submenu.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => request.path} %>
    </li>
    <li <%= "class='selected'" if params[:action] == "index" %>>
      <%= link_to t('.inbox'), admin_inquiries_url, :class => "email_icon" %>
    </li>
<!-- hiding spam button    <li <%#= "class='selected'" if params[:action] == "spam" %>>
      <%# if @spam_count > 0  %>
        <%#= link_to "#{t('.spam')} (#{@spam_count})", spam_admin_inquiries_url, :class => "spam_icon" %>
      <%# else %>
        <%#= link_to t('.spam'), spam_admin_inquiries_url, :class => "spam_empty_icon" %>
      <%# end %>
    </li> -->
    <li>
      <%= link_to t('.update_notified'),
                    edit_admin_inquiry_setting_url(:inquiry_notification_recipients, :dialog => true, :height => 300),
                    :class => "user_comment_icon" %>
    </li>
    <li>
      <%= link_to t('.edit_confirmation_email'),
                  edit_admin_inquiry_setting_url(:inquiry_confirmation_body, :dialog => true),
                  :class => "edit_email_icon" %>
    </li>
  </ul>
</div>

app/views/admin/inquiries/index.html.erb
<%= render :partial => "submenu" %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @inquiries.any? %>
      <%= will_paginate @inquiries %>
      <ul>
        <%= render :partial => "inquiry", :collection => @inquiries %>
      </ul>
      <%= will_paginate @inquiries %>
    <% else %>
      <p><%= t('shared.admin.search.no_results') %></p>
    <% end %>
  <% else %>
    <% if @inquiries.any? -%>
      <%= will_paginate @inquiries %>
      <% group_by_date(@inquiries).each do |container| %>
        <h3><%= l((inquiry_group = container.last).first.created_at, :format => :short) %></h3>
        <ul>
          <%= render :partial => 'inquiry', :collection => inquiry_group %>
        </ul>
      <% end %>
      <%= will_paginate @inquiries %>
    <% else -%>
      <p>
        <strong><%= t(".no_#{action_name == 'index' ? 'inquiries' : 'spam'}") %></strong>
      </p>
    <% end -%>
  <% end %>
</div>

app/views/admin/inquiries/show.html.erb
<div id='actions'>
  <h2><%= t('.details')%></h2>
  <p>
    <strong><%= t('.age') %>:</strong> <%= time_ago_in_words(@inquiry.created_at) %>
  </p>
  <% if @inquiry.spam? %>
    <p>
      <strong><%= t('.spam') %>:</strong> <%= t('.spam_yes') %>
    </p>
  <% end %>
  <h2><%= t('.actions') %></h2>
  <ul>
    <li>
      <%= link_to t('.back_to_all_inquiries'), {:action => 'index'}, :class => "back_icon" %>
    </li>
    <li>
      <%= link_to t('admin.inquiries.delete'),
        admin_inquiry_url(@inquiry),
        :class => 'delete_icon no-tooltip confirm-delete',
        :title => t('admin.inquiries.delete'),
        :confirm => t('shared.admin.delete.message', :title => @inquiry.name),
        :method => :delete %>
    </li>
  </ul>
</div>
<div id='records'>
  <h2><%= t('.inquiry') %></h2>
  <table id='inquiry'>
    <tr>
      <td>
        <strong><%= t('.to') %></strong>
      </td>
      <td>
        <%= RefinerySetting[:site_name] %>
      </td>
    </tr>
    <tr>
      <td>
        <strong><%= t('.from') %></strong>
      </td>
      <td>
        <%= @inquiry.name %> [<%= mail_to @inquiry.email, @inquiry.email, {:title => t('.click_to_email')} %>]
      </td>
    </tr>
    <% unless @inquiry.company.blank? %>
      <tr>
        <td><strong>Company</strong></td>
        <td><%= @inquiry.company %></td>
      </tr>
    <% end %>
    <% unless @inquiry.address.blank? %>
      <tr>
        <td><strong>Address</strong></td>
        <td><%= @inquiry.address %></td>
      </tr>
    <% end %>
    <% unless @inquiry.city.blank? && @inquiry.state.blank? && @inquiry.zip.blank? %>
      <tr>
        <td><strong>City / State / Zip</strong></td>
        <td>
          <% unless @inquiry.city.blank? %>
            <%= @inquiry.city %>
          <% end %>
          <% unless @inquiry.state.blank? %>
            <%= @inquiry.state %>
          <% end %>
          <% unless @inquiry.zip.blank? %>
            <%= @inquiry.zip %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% unless @inquiry.country.blank? %>
      <tr>
        <td><strong>Country</strong></td>
        <td><%= @inquiry.country %></td>
      </tr>
    <% end %>
      <tr>
        <td>
          <strong><%= t('.phone') %></strong>
        </td>
        <td>
          <%= @inquiry.phone %>
        </td>
      </tr>
    <tr>
      <td>
        <strong><%= t('.date') %></strong>
      </td>
      <td>
        <%= l(Date.parse(@inquiry.created_at.to_s), :format => :long) %>
      </td>
    </tr>
    <tr>
      <td valign='top'>
        <strong><%= t('.message') %></strong>
      </td>
      <td>
        <%= simple_format @inquiry.message, :style => 'margin-top: 0' %>
      </td>
    </tr>
  </table>
</div>

app/views/admin/inquiry_settings/_confirmation_email_form.html.erb
<%= form_for([:admin, @refinery_setting], :url => (@url_override || @url)) do |f| %>

  <p>
    <%= t('.explanation') %>
  </p>
  <p>
    <%= t('.below_edit_email_sent') %>
  </p>
  <table id='inquiry'>
    <tr>
      <td>
        <label class='stripped'><%= t('.to') %></label>
      </td>
      <td>
        <%= t('.the_customer_making_inquiry') %>
      </td>
    </tr>
    <tr>
      <td>
        <label class='stripped'><%= t('.from') %></label>
      </td>
      <td>
        <%= "#{RefinerySetting[:site_name]} &lt;no-reply@#{request.domain(RefinerySetting.find_or_set(:tld_length, 1))}&gt;".html_safe %>
      </td>
    </tr>
    <tr>
      <td>
        <label class='stripped'><%= t('.subject') %></label>
      </td>
      <td>
        <%= text_field_tag 'subject', InquirySetting.confirmation_subject,
                           :class => 'widest' %>
      </td>
    </tr>
    <tr>
      <td valign='top'>
        <%= f.label :value, t('.message'),
                    :class => 'stripped' %>
      </td>
      <td>
        <%= f.text_area :value, :value => f.object.value, # required, we can't use :value
                        :rows => "5",
                        :class => 'widest' %>
        <br/>
        <em><%= t('.note') %></em>
      </td>
    </tr>
  </table>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :cancel_url => admin_inquiries_url,
               :hide_delete => true
             } %>
<% end %>

app/views/admin/inquiry_settings/_notification_recipients_form.html.erb
<%= form_for([:admin, @refinery_setting], :url => (@url_override || @url)) do |f| %>

  <div class='field'>
    <span class='label_with_help'>
      <%= f.label :value, t('.inquiry_settings_value_name') %>
    </span>
    <%= f.text_field :value, :value => f.object.value, # required, we can't use :value
                     :class => "larger widest" %>
  </div>

  <p>
    <%= t('.hint') %>
  </p>
  <p>
    <%= t('.example') %>
  </p>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :cancel_url => admin_inquiries_url,
               :hide_delete => true
             } %>
<% end %>

app/views/admin/inquiry_settings/edit.html.erb
<% if @refinery_setting.name.to_s.titleize == "Inquiry Notification Recipients" %>
  <%= render :partial => "notification_recipients_form", :locals => {:edit => true} -%>
<% else %>
  <%= render :partial => "confirmation_email_form", :locals => {:edit => true} -%>
<% end %>

app/views/inquiries/new.html.erb
<div id="main">
  <%= render :partial => "/shared/content_page" %> 
  <div class='inquiries'>
<%#=raw @page[Page.default_parts.first.to_sym] %>

    <%= form_for @inquiry do |f| %>
      <%= render :partial => "/shared/admin/error_messages",
        :locals => {
        :object => @inquiry,
        :include_object_name => true
      } %>
      <div class='field'>
        <%= f.required_label :name %>
        <%= f.text_field :name %>
      </div>
      <div class='field'>
        <%= f.required_label :company %>
        <%= f.text_field :company %>
      </div>
      <div class='field'>
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>
      <div class='field'>
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div class='field'>
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>
      <div class="field">
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </div>
      <div class="field">
        <%= f.label :country %>
        <%= f.text_field :country %>
      </div>
      <div class='field'>
        <%= f.required_label :phone %>
        <%= f.text_field :phone %>
      </div>
      <div class='field'>
        <%= f.required_label :email %>
        <%= f.text_field :email %>
      </div>
      
      <span class="note">* Required field</span>
      <br /><br />
      <div class='field message_field'>
        <%= f.required_label "How Can We Help You?"  %><br />
        <%= f.text_area :message, :rows => 8, :cols => 47 %>
      </div>
      
      <div class='field'>
          <%= recaptcha_tags %>
      </div>
      
      <div class='actions'>
        <%= f.submit t('.send') %>
        <%= link_to t('.privacy_policy'), "/pages/privacy-policy", :id => "privacy_link" if RefinerySetting.find_or_set(:show_contact_privacy_link, false) %>
      </div>
      <br /><br />
    <% end %>
  </div>
</div>
<div id="main-side">
  <% @page.snippets.each do |s| %>
    <%= raw s.body %>
  <% end %>
</div>

app/views/inquiries/thank_you.html.erb
<div id="main-secondary">
  <%= render :partial => "/shared/content_page" %>
</div>